version: '3.8'
services:
  # Docker connection string: postgres://postgres:admin@localhost:5432/

  postgres:
    image: postgres:lastest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
