version: '3.8'
services:
  # Docker connection string: postgres://postgres:admin@localhost:5432/

  postgres:
    container_name: db
    image: postgres:lastest
    restart: always
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
  node_app:
    container_name: node_app
    build: .
    ports:
      - 1234:5000
    depends_on:
      - db
    env_file:
      - .env
volumes:
  postgres:
